### ISSUE TITLE
is this project still active?

### ISSUE THREAD

**Issue by mingfang** [mdawar/terraformjs#10]

**Comment by mdawar** [comment]
Hey,

You can still use it if you want (This tool generates [JSON config](https://developer.hashicorp.com/terraform/language/syntax/json)), but you're better off using [HCL](https://developer.hashicorp.com/terraform/language/syntax/configuration) directly.

When this tool was created HCL didn't have as many features as it does now, most of what you need can be done with HCL now without the need for a programming language.

**Comment by mingfang** [comment]
Thanks for the response.
I've learn a lot from using this tool.
Thanks
